# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "463f97a025f2b5e5044f69fa2ca6d93f"
name = "TrackBack-dev"
application_url = "https://therapeutic-meetings-penalty-possibility.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "shop/update" ]
  uri = "/webhooks/shop/update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_orders,read_products,read_returns,read_store_credit_account_transactions,read_store_credit_accounts,write_draft_orders,write_gift_cards,write_orders,write_products,write_returns,write_store_credit_account_transactions"

[auth]
redirect_urls = [
  "https://therapeutic-meetings-penalty-possibility.trycloudflare.com/auth/callback",
  "https://therapeutic-meetings-penalty-possibility.trycloudflare.com/auth/shopify/callback",
  "https://therapeutic-meetings-penalty-possibility.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://therapeutic-meetings-penalty-possibility.trycloudflare.com/proxy"
subpath = "returns"
prefix = "apps"

[pos]
embedded = false
