/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: { sans: ['Inter', 'system-ui', 'sans-serif'] },
      colors: {
        bg:       'rgb(var(--c-bg) / <alpha-value>)',
        surface:  'rgb(var(--c-surface) / <alpha-value>)',
        elevated: 'rgb(var(--c-elevated) / <alpha-value>)',
        border:   'rgb(var(--c-border) / <alpha-value>)',
        divider:  'rgb(var(--c-divider) / <alpha-value>)',
        ink:      'rgb(var(--c-ink) / <alpha-value>)',
        muted:    'rgb(var(--c-muted) / <alpha-value>)',
        faint:    'rgb(var(--c-faint) / <alpha-value>)',
        accent:   'rgb(var(--c-accent) / <alpha-value>)',
        accent2:  'rgb(var(--c-accent2) / <alpha-value>)',
        ok:       '#22C55E',
        warn:     '#F59E0B',
        danger:   '#EF4444',
        info:     '#3B82F6',
        violet:   '#8B5CF6',
      },
      boxShadow: {
        soft:  '0 1px 0 rgba(255,255,255,0.04) inset, 0 1px 2px rgba(0,0,0,0.4)',
        pop:   '0 12px 32px rgba(0,0,0,0.55), 0 2px 4px rgba(0,0,0,0.4)',
        glow:  '0 0 0 1px rgba(108,99,255,0.35), 0 8px 28px -4px rgba(108,99,255,0.45)',
        lift:  '0 10px 30px -10px rgba(0,0,0,0.65), 0 4px 10px -4px rgba(0,0,0,0.4)',
        ring:  '0 0 0 4px rgba(108,99,255,0.18)',
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        smooth: 'cubic-bezier(0.22, 1, 0.36, 1)',
        snap:   'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      keyframes: {
        slideUp:   { '0%': { transform: 'translateY(10px)', opacity: '0' },  '100%': { transform: 'translateY(0)',  opacity: '1' } },
        slideDown: { '0%': { transform: 'translateY(-8px)', opacity: '0' },  '100%': { transform: 'translateY(0)',  opacity: '1' } },
        slideInR:  { '0%': { transform: 'translateX(12px)', opacity: '0' },  '100%': { transform: 'translateX(0)',  opacity: '1' } },
        fadeIn:    { '0%': { opacity: '0' },                                 '100%': { opacity: '1' } },
        scaleIn:   { '0%': { transform: 'scale(.96)',       opacity: '0' },  '100%': { transform: 'scale(1)',       opacity: '1' } },
        popIn:     { '0%': { transform: 'scale(.92)',       opacity: '0' },  '60%': { transform: 'scale(1.02)',     opacity: '1' }, '100%': { transform: 'scale(1)' } },
        pulseSoft: { '0%,100%': { opacity: '1' }, '50%': { opacity: '.55' } },
        shimmer:   { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        glowPulse: { '0%,100%': { boxShadow: '0 0 0 0 rgba(108,99,255,0.45)' }, '50%': { boxShadow: '0 0 0 8px rgba(108,99,255,0)' } },
        floatY:    { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-3px)' } },
        spinSlow:  { 'to': { transform: 'rotate(360deg)' } },
      },
      animation: {
        slideUp:   'slideUp .32s cubic-bezier(0.22, 1, 0.36, 1) both',
        slideDown: 'slideDown .28s cubic-bezier(0.22, 1, 0.36, 1) both',
        slideInR:  'slideInR .32s cubic-bezier(0.22, 1, 0.36, 1) both',
        fadeIn:    'fadeIn .22s ease-out both',
        scaleIn:   'scaleIn .25s cubic-bezier(0.22, 1, 0.36, 1) both',
        popIn:     'popIn .38s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        pulseSoft: 'pulseSoft 2s ease-in-out infinite',
        shimmer:   'shimmer 1.8s linear infinite',
        glowPulse: 'glowPulse 2.2s ease-in-out infinite',
        floatY:    'floatY 3.4s ease-in-out infinite',
        spinSlow:  'spinSlow 6s linear infinite',
      },
      backdropBlur: {
        xs: '2px',
      },
    }
  },
  plugins: [],
}
