/**
 * Lucide icons that TrackBack renders by name through <Icon name="…" />.
 *
 * Importing lucide's full `icons` map shipped every icon (~800 kB of JS) to
 * each page, the customer portal included. Register an icon here before using
 * it by name: tests/icons.test.ts fails when a name used in app/ is missing,
 * and <Icon> renders nothing for unknown names.
 */
import * as L from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  ArrowLeft: L.ArrowLeft,
  ArrowLeftRight: L.ArrowLeftRight,
  ArrowRight: L.ArrowRight,
  BadgeCheck: L.BadgeCheck,
  Ban: L.Ban,
  Banknote: L.Banknote,
  Bell: L.Bell,
  Blocks: L.Blocks,
  Bold: L.Bold,
  BookOpen: L.BookOpen,
  Calendar: L.Calendar,
  CalendarClock: L.CalendarClock,
  Camera: L.Camera,
  ChartLine: L.ChartLine,
  Check: L.Check,
  ChevronDown: L.ChevronDown,
  ChevronLeft: L.ChevronLeft,
  ChevronRight: L.ChevronRight,
  ChevronUp: L.ChevronUp,
  Circle: L.Circle,
  CircleCheck: L.CircleCheck,
  CircleX: L.CircleX,
  Clock: L.Clock,
  Clock3: L.Clock3,
  CloudDownload: L.CloudDownload,
  Coins: L.Coins,
  Copy: L.Copy,
  CreditCard: L.CreditCard,
  DollarSign: L.DollarSign,
  Download: L.Download,
  ExternalLink: L.ExternalLink,
  Eye: L.Eye,
  FileCheck: L.FileCheck,
  FileText: L.FileText,
  FileX: L.FileX,
  Gift: L.Gift,
  Globe: L.Globe,
  GripVertical: L.GripVertical,
  Headphones: L.Headphones,
  Heart: L.Heart,
  Image: L.Image,
  Inbox: L.Inbox,
  Info: L.Info,
  KeyRound: L.KeyRound,
  Languages: L.Languages,
  Layers: L.Layers,
  LayoutDashboard: L.LayoutDashboard,
  LayoutTemplate: L.LayoutTemplate,
  Leaf: L.Leaf,
  LifeBuoy: L.LifeBuoy,
  Lightbulb: L.Lightbulb,
  Link: L.Link,
  Link2: L.Link2,
  ListChecks: L.ListChecks,
  Loader: L.Loader,
  LoaderCircle: L.LoaderCircle,
  Lock: L.Lock,
  LogOut: L.LogOut,
  Mail: L.Mail,
  MapPin: L.MapPin,
  Maximize2: L.Maximize2,
  MessageCircle: L.MessageCircle,
  MessageCircleMore: L.MessageCircleMore,
  MessageCircleQuestionMark: L.MessageCircleQuestionMark,
  MessageSquare: L.MessageSquare,
  Monitor: L.Monitor,
  Moon: L.Moon,
  Package: L.Package,
  PackageCheck: L.PackageCheck,
  PackageOpen: L.PackageOpen,
  PackagePlus: L.PackagePlus,
  Paintbrush: L.Paintbrush,
  PaintbrushVertical: L.PaintbrushVertical,
  Palette: L.Palette,
  PanelBottom: L.PanelBottom,
  Phone: L.Phone,
  Plus: L.Plus,
  Receipt: L.Receipt,
  RefreshCcw: L.RefreshCcw,
  RefreshCw: L.RefreshCw,
  Reply: L.Reply,
  Rocket: L.Rocket,
  RotateCcw: L.RotateCcw,
  Save: L.Save,
  Search: L.Search,
  Send: L.Send,
  Settings: L.Settings,
  Settings2: L.Settings2,
  Shield: L.Shield,
  ShieldAlert: L.ShieldAlert,
  ShieldCheck: L.ShieldCheck,
  Shirt: L.Shirt,
  ShoppingBag: L.ShoppingBag,
  Smartphone: L.Smartphone,
  Sparkles: L.Sparkles,
  Store: L.Store,
  Sun: L.Sun,
  Tag: L.Tag,
  Ticket: L.Ticket,
  Timeline: L.Timeline,
  Trash2: L.Trash2,
  TrendingDown: L.TrendingDown,
  TriangleAlert: L.TriangleAlert,
  Truck: L.Truck,
  Type: L.Type,
  Upload: L.Upload,
  View: L.View,
  Wallet: L.Wallet,
  Watch: L.Watch,
  Webhook: L.Webhook,
  X: L.X,
  Zap: L.Zap,
};

export function hasIcon(name: string | null | undefined): name is string {
  return !!name && Object.prototype.hasOwnProperty.call(ICONS, name);
}
